### ISSUE TITLE
Kitchen test failing

### ISSUE THREAD

**Issue by shivam99aa** [chrisroberts/kitchen-lxc#9]
I am getting following error when i try to run kitchen test. 

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [private method `config' called for #<Kitchen::Driver::Lxc:0x00000001982488>]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

This is my .kitchen.yml file 

```

---
driver:
  name: lxc

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu

suites:
  - name: default
    run_list:
    attributes:
```
